name: flutter_bluetooth_serial_example
version: 0.4.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scoped_model: ^2.0.0-nullsafety.0
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_bluetooth_serial: ^0.4.0

  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
